apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.service.vote.nodePort }}
  type: NodePort
