apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote-container
          image: {{ .Values.image.vote.repository }}:{{ .Values.image.vote.tag }}
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: voting-app-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: voting-app-config
                  key: REDIS_PORT
