apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: mongo
spec:
  type: {{.Values.mongoExpress.service.type}}
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: {{.Values.mongoExpress.service.port}}
      targetPort: 27017
