apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongo
spec:
  type: {{.Values.mongo.service.type}}
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: {{.Values.mongo.service.port}}
      targetPort: 8081
